name: test
run-name: Test Application

on:
    - workflow_call
    - workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'maven'

            - name: Run tests
              run: mvn clean test
